# Service port
server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

spring:
  application:
    name: AWS Git Demo

  # Profiles
  profiles:
    default: local

  # Datasource properties
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/aws_git_demo_db
    username:
    password:
    hikari:
      maximum-pool-size: 2

  jpa:
    show-sql: true
    open-in-view: false

  liquibase:
    enabled: true
    change-log: classpath:/liquibase/master.xml
