#Service port
server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'

spring:
  application:
    name: AWS Git Demo

  profiles:
    default: local

  #Datasource properties
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://aws-demo-db.c1qae24qscqv.ap-south-1.rds.amazonaws.com:3306/aws_git_demo_db
    username: admin
    password: aws-demo
    hikari:
      maximum-pool-size: 2
  jpa:
    show-sql: true
    open-in-view: false

  liquibase:
    enabled: true
    change-log: classpath:/liquibase/master.xml

springdoc:
  api-docs:
    path: /api-docs